#!/bin/bash
cd "$(dirname "$0")"
BDIR="$HOME/.vim/bundle"
VURL="https://github.com/VundleVim/Vundle.vim.git"
VDIR="$BDIR/Vundle.vim"

if [ ! -d "$BDIR" ]; then mkdir "$BDIR"; fi
if [ ! -d "$VDIR" ]; then git clone "$VURL" "$VDIR"; fi
SETUP_SCRIPTS=()
(
    cd plugins
    echo '" Do not edit this file!  It is generated by setup.sh'
    echo "set nocompatible"
    echo "filetype off"
    echo "set runtimepath+=$VDIR"
    echo "call vundle#begin()"
    echo "Plugin 'VundleVim/Vundle.vim'"
    for I in *.vim; do
        sed -n 's,^" *Plugin,Plugin,p' $I
        SS="${I%.vim}.sh"
        if [ -x "$SS" ]; then SETUP_SCRIPTS+=( "$SS" ); fi
    done
    echo "call vundle#end()"
    echo "filetype plugin indent on"
    for I in *.vim; do echo "source ~/.vim/plugins/$I"; done
) > plugins.vim

#vim +PluginInstall +qall
vim -i NONE -c VundleUpdate -c quitall

for SS in "${SETUP_SCRIPTS[@]}"; do
    plugins/$SS
done

cd "$HOME"
for V in "$HOME/.vimrc" "$HOME/.gvimrc"; do
    ln -sf "$HOME/.vim/vimrc" "$V"
# If symlinks don't work on windows, then this option will probably be
# better there.
#   if [ -e $V ]; then if [ ! -f $HOME/$V ]; then rm -f $HOME/$V; fi; fi
#   echo 'source $HOME/.vim/vimrc' > $HOME/$V
done
