#!/bin/bash
cd "$(dirname "$0")"
BDIR="$HOME/.vim/bundle"
VURL="https://github.com/VundleVim/Vundle.vim.git"
VDIR="$BDIR/Vundle.vim"

if [ ! -d "$BDIR" ]; then mkdir "$BDIR"; fi
if [ ! -d "$VDIR" ]; then git clone "$VURL" "$VDIR"; fi
(
    echo '" Do not edit this file!  It is generated by setup.sh'
    echo "set nocompatible"
    echo "filetype off"
    echo "set runtimepath+=$VDIR"
    echo "call vundle#begin()"
    echo "Plugin 'VundleVim/Vundle.vim'"
    sed -n 's,^" *Plugin,Plugin,p' plugins/*.vim
    echo "call vundle#end()"
    echo "filetype plugin indent on"
    for I in plugins/*.vim; do echo "source ~/.vim/$I"; done
) > plugins.vim

vim +PluginInstall +qall

if [ -d "$BDIR/term_for_vim" ]; then
    ( cd "$BDIR/term_for_vim" && npm install )
fi
